/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VaultsIndexImport } from './routes/vaults/index'
import { Route as VaultsCreateImport } from './routes/vaults/create'
import { Route as DemoStoreImport } from './routes/demo.store'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VaultsIndexRoute = VaultsIndexImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => rootRoute,
} as any)

const VaultsCreateRoute = VaultsCreateImport.update({
  id: '/vaults/create',
  path: '/vaults/create',
  getParentRoute: () => rootRoute,
} as any)

const DemoStoreRoute = DemoStoreImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreImport
      parentRoute: typeof rootRoute
    }
    '/vaults/create': {
      id: '/vaults/create'
      path: '/vaults/create'
      fullPath: '/vaults/create'
      preLoaderRoute: typeof VaultsCreateImport
      parentRoute: typeof rootRoute
    }
    '/vaults/': {
      id: '/vaults/'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/vaults/create': typeof VaultsCreateRoute
  '/vaults': typeof VaultsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/vaults/create': typeof VaultsCreateRoute
  '/vaults': typeof VaultsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo/store': typeof DemoStoreRoute
  '/vaults/create': typeof VaultsCreateRoute
  '/vaults/': typeof VaultsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/store' | '/vaults/create' | '/vaults'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/store' | '/vaults/create' | '/vaults'
  id: '__root__' | '/' | '/demo/store' | '/vaults/create' | '/vaults/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoStoreRoute: typeof DemoStoreRoute
  VaultsCreateRoute: typeof VaultsCreateRoute
  VaultsIndexRoute: typeof VaultsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoStoreRoute: DemoStoreRoute,
  VaultsCreateRoute: VaultsCreateRoute,
  VaultsIndexRoute: VaultsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo/store",
        "/vaults/create",
        "/vaults/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo/store": {
      "filePath": "demo.store.tsx"
    },
    "/vaults/create": {
      "filePath": "vaults/create.tsx"
    },
    "/vaults/": {
      "filePath": "vaults/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
