/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VaultsImport } from './routes/vaults'
import { Route as PreferencesImport } from './routes/preferences'
import { Route as IndexImport } from './routes/index'
import { Route as DemoStoreImport } from './routes/demo.store'

// Create/Update Routes

const VaultsRoute = VaultsImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRoute,
} as any)

const PreferencesRoute = PreferencesImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoStoreRoute = DemoStoreImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesImport
      parentRoute: typeof rootRoute
    }
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsImport
      parentRoute: typeof rootRoute
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/vaults': typeof VaultsRoute
  '/demo/store': typeof DemoStoreRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/vaults': typeof VaultsRoute
  '/demo/store': typeof DemoStoreRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/preferences': typeof PreferencesRoute
  '/vaults': typeof VaultsRoute
  '/demo/store': typeof DemoStoreRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preferences' | '/vaults' | '/demo/store'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preferences' | '/vaults' | '/demo/store'
  id: '__root__' | '/' | '/preferences' | '/vaults' | '/demo/store'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreferencesRoute: typeof PreferencesRoute
  VaultsRoute: typeof VaultsRoute
  DemoStoreRoute: typeof DemoStoreRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreferencesRoute: PreferencesRoute,
  VaultsRoute: VaultsRoute,
  DemoStoreRoute: DemoStoreRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/preferences",
        "/vaults",
        "/demo/store"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/preferences": {
      "filePath": "preferences.tsx"
    },
    "/vaults": {
      "filePath": "vaults.tsx"
    },
    "/demo/store": {
      "filePath": "demo.store.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
